/**
 * @brief Flash registers
 */

#include "registers/helpers.h"

#pragma once

#define FLASH_BASE 0x40022000

#define FLASH_ACR_OFFSET     0x00000000
#define FLASH_PECR_OFFSET    0x00000004
#define FLASH_PDKEYR_OFFSET  0x00000008
#define FLASH_PKEYR_OFFSET   0x0000000C
#define FLASH_PRGKEYR_OFFSET 0x00000010
#define FLASH_OPTKEYR_OFFSET 0x00000014
#define FLASH_SR_OFFSET      0x00000018
#define FLASH_OPTR_OFFSET    0x0000001C
#define FLASH_WRPROT1_OFFSET 0x00000020
#define FLASH_WRPROT2_OFFSET 0x00000024


#define FLASH_ACR     REGISTER(FLASH_BASE + FLASH_ACR_OFFSET)
#define FLASH_PECR    REGISTER(FLASH_BASE + FLASH_PECR_OFFSET)
#define FLASH_PDKEYR  REGISTER(FLASH_BASE + FLASH_PDKEYR_OFFSET)
#define FLASH_PKEYR   REGISTER(FLASH_BASE + FLASH_PKEYR_OFFSET)
#define FLASH_PRGKEYR REGISTER(FLASH_BASE + FLASH_PRGKEYR_OFFSET)
#define FLASH_OPTKEYR REGISTER(FLASH_BASE + FLASH_OPTKEYR_OFFSETR)
#define FLASH_SR      REGISTER(FLASH_BASE + FLASH_SR_OFFSET)
#define FLASH_OPTR    REGISTER(FLASH_BASE + FLASH_OPTR_OFFSET)
#define FLASH_WRPROT1 REGISTER(FLASH_BASE + FLASH_WRPROT1_OFFSET)
#define FLASH_WRPROT2 REGISTER(FLASH_BASE + FLASH_WRPROT2_OFFSET)

