/**
 * @brief GPIO control registers
 */

#include "registers/helpers.h"

#pragma once


#define GPIO_A_BASE 0x50000000
#define GPIO_B_BASE 0x50000400
#define GPIO_C_BASE 0x50000800
#define GPIO_D_BASE 0x50000C00
#define GPIO_E_BASE 0x50001000
#define GPIO_H_BASE 0x50001C00

#define GPIO_MODER_OFFSET   0x00000000
#define GPIO_OTYPER_OFFSET  0x00000004
#define GPIO_OSPEEDR_OFFSET 0x00000008
#define GPIO_PUPDR_OFFSET   0x0000000C
#define GPIO_IDR_OFFSET     0x00000010
#define GPIO_ODR_OFFSET     0x00000014
#define GPIO_BSRR_OFFSET    0x00000018
#define GPIO_LCKR_OFFSET    0x0000001C
#define GPIO_AFRL_OFFSET    0x00000020
#define GPIO_AFRH_OFFSET    0x00000024
#define GPIO_BRR_OFFSET     0x00000028


#define GPIO_A_MODER   REGISTER(GPIO_A_BASE + GPIO_MODER_OFFSET)
#define GPIO_A_OTYPER  REGISTER(GPIO_A_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_A_OSPEEDR REGISTER(GPIO_A_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_A_PUPDR   REGISTER(GPIO_A_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_A_IDR     REGISTER(GPIO_A_BASE + GPIO_IDR_OFFSET)
#define GPIO_A_ODR     REGISTER(GPIO_A_BASE + GPIO_ODR_OFFSET)
#define GPIO_A_BSRR    REGISTER(GPIO_A_BASE + GPIO_BSRR_OFFSET)
#define GPIO_A_LCKR    REGISTER(GPIO_A_BASE + GPIO_LCKR_OFFSET)
#define GPIO_A_AFRL    REGISTER(GPIO_A_BASE + GPIO_AFRL_OFFSET)
#define GPIO_A_AFRH    REGISTER(GPIO_A_BASE + GPIO_AFRH_OFFSET)
#define GPIO_A_BRR     REGISTER(GPIO_A_BASE + GPIO_BRR_OFFSET)


#define GPIO_B_MODER   REGISTER(GPIO_B_BASE + GPIO_MODER_OFFSET)
#define GPIO_B_OTYPER  REGISTER(GPIO_B_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_B_OSPEEDR REGISTER(GPIO_B_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_B_PUPDR   REGISTER(GPIO_B_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_B_IDR     REGISTER(GPIO_B_BASE + GPIO_IDR_OFFSET)
#define GPIO_B_ODR     REGISTER(GPIO_B_BASE + GPIO_ODR_OFFSET)
#define GPIO_B_BSRR    REGISTER(GPIO_B_BASE + GPIO_BSRR_OFFSET)
#define GPIO_B_LCKR    REGISTER(GPIO_B_BASE + GPIO_LCKR_OFFSET)
#define GPIO_B_AFRL    REGISTER(GPIO_B_BASE + GPIO_AFRL_OFFSET)
#define GPIO_B_AFRH    REGISTER(GPIO_B_BASE + GPIO_AFRH_OFFSET)
#define GPIO_B_BRR     REGISTER(GPIO_B_BASE + GPIO_BRR_OFFSET)


#define GPIO_C_MODER   REGISTER(GPIO_C_BASE + GPIO_MODER_OFFSET)
#define GPIO_C_OTYPER  REGISTER(GPIO_C_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_C_OSPEEDR REGISTER(GPIO_C_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_C_PUPDR   REGISTER(GPIO_C_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_C_IDR     REGISTER(GPIO_C_BASE + GPIO_IDR_OFFSET)
#define GPIO_C_ODR     REGISTER(GPIO_C_BASE + GPIO_ODR_OFFSET)
#define GPIO_C_BSRR    REGISTER(GPIO_C_BASE + GPIO_BSRR_OFFSET)
#define GPIO_C_LCKR    REGISTER(GPIO_C_BASE + GPIO_LCKR_OFFSET)
#define GPIO_C_AFRL    REGISTER(GPIO_C_BASE + GPIO_AFRL_OFFSET)
#define GPIO_C_AFRH    REGISTER(GPIO_C_BASE + GPIO_AFRH_OFFSET)
#define GPIO_C_BRR     REGISTER(GPIO_C_BASE + GPIO_BRR_OFFSET)


#define GPIO_D_MODER   REGISTER(GPIO_D_BASE + GPIO_MODER_OFFSET)
#define GPIO_D_OTYPER  REGISTER(GPIO_D_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_D_OSPEEDR REGISTER(GPIO_D_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_D_PUPDR   REGISTER(GPIO_D_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_D_IDR     REGISTER(GPIO_D_BASE + GPIO_IDR_OFFSET)
#define GPIO_D_ODR     REGISTER(GPIO_D_BASE + GPIO_ODR_OFFSET)
#define GPIO_D_BSRR    REGISTER(GPIO_D_BASE + GPIO_BSRR_OFFSET)
#define GPIO_D_LCKR    REGISTER(GPIO_D_BASE + GPIO_LCKR_OFFSET)
#define GPIO_D_AFRL    REGISTER(GPIO_D_BASE + GPIO_AFRL_OFFSET)
#define GPIO_D_AFRH    REGISTER(GPIO_D_BASE + GPIO_AFRH_OFFSET)
#define GPIO_D_BRR     REGISTER(GPIO_D_BASE + GPIO_BRR_OFFSET)


#define GPIO_E_MODER   REGISTER(GPIO_E_BASE + GPIO_MODER_OFFSET)
#define GPIO_E_OTYPER  REGISTER(GPIO_E_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_E_OSPEEDR REGISTER(GPIO_E_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_E_PUPDR   REGISTER(GPIO_E_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_E_IDR     REGISTER(GPIO_E_BASE + GPIO_IDR_OFFSET)
#define GPIO_E_ODR     REGISTER(GPIO_E_BASE + GPIO_ODR_OFFSET)
#define GPIO_E_BSRR    REGISTER(GPIO_E_BASE + GPIO_BSRR_OFFSET)
#define GPIO_E_LCKR    REGISTER(GPIO_E_BASE + GPIO_LCKR_OFFSET)
#define GPIO_E_AFRL    REGISTER(GPIO_E_BASE + GPIO_AFRL_OFFSET)
#define GPIO_E_AFRH    REGISTER(GPIO_E_BASE + GPIO_AFRH_OFFSET)
#define GPIO_E_BRR     REGISTER(GPIO_E_BASE + GPIO_BRR_OFFSET)


#define GPIO_H_MODER   REGISTER(GPIO_H_BASE + GPIO_MODER_OFFSET)
#define GPIO_H_OTYPER  REGISTER(GPIO_H_BASE + GPIO_OTYPER_OFFSET)
#define GPIO_H_OSPEEDR REGISTER(GPIO_H_BASE + GPIO_OSPEEDR_OFFSET)
#define GPIO_H_PUPDR   REGISTER(GPIO_H_BASE + GPIO_PUPDR_OFFSET)
#define GPIO_H_IDR     REGISTER(GPIO_H_BASE + GPIO_IDR_OFFSET)
#define GPIO_H_ODR     REGISTER(GPIO_H_BASE + GPIO_ODR_OFFSET)
#define GPIO_H_BSRR    REGISTER(GPIO_H_BASE + GPIO_BSRR_OFFSET)
#define GPIO_H_LCKR    REGISTER(GPIO_H_BASE + GPIO_LCKR_OFFSET)
#define GPIO_H_AFRL    REGISTER(GPIO_H_BASE + GPIO_AFRL_OFFSET)
#define GPIO_H_AFRH    REGISTER(GPIO_H_BASE + GPIO_AFRH_OFFSET)
#define GPIO_H_BRR     REGISTER(GPIO_H_BASE + GPIO_BRR_OFFSET)


